from certificate_copycat.copycat_generator import CertificateCopyCatGenerator
from certificate_copycat.copycat_result import CertificateCopyCatResult

__ALL__ = [CertificateCopyCatGenerator, CertificateCopyCatResult]
